name: CI Deploy Functions & Hosting

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install root dependencies
        run: |
          npm ci

      - name: Install functions dependencies
        run: |
          cd functions
          npm ci

      - name: Build functions
        run: |
          cd functions
          npm run build

      - name: Set functions config (GENAI key)
        if: ${{ secrets.GENAI_KEY }}
        run: |
          cd functions
          npx --yes firebase-tools functions:config:set genai.key="${{ secrets.GENAI_KEY }}"


      - name: Firebase deploy
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
